name: portfolio
description: A simple portfolio about myself after working a year in flutter.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  flutter_riverpod: ^2.5.1
  flutter_staggered_grid_view: ^0.7.0
  url_launcher: ^6.1.5
  scroll_to_index: ^3.0.1
  http: ^1.2.2
  particles_flutter: ^1.0.0
  material_design_icons_flutter: ^7.0.7296
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
  fonts:
    - family: sfmono
      fonts:
        - asset: fonts/sfmono.otf
